import './globals.css';
import { Inter } from 'next/font/google';

// eslint-disable-next-line @typescript-eslint/quotes
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: `Create Next App`,
  description: `Generated by create next app`,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { title } = metadata;

  return (
    <html lang="pt-BR">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
